# This is for testing on travies only
# For production we recommend to rather use
# image: kartoza/pg-backup
# in the dbbackup service
db:
  image: kartoza/postgis
  environment:
    - USERNAME=docker
    - PASS=docker

dbbackup:
  build: .
  volumes:
    - ./backup:/backup
  environment:
    - DUMPPREFIX=watchkeeper
    - PGHOST=db
    - PGUSER=docker
    - PGPASSWORD=docker
    - PGPORT=5432
  links:
    - db:db