# This is for testing on travies only
# For production we recommend to rather use
# image: kartoza/pg-backup
# in the dbbackup service
sftpbackup:
  build: .
  volumes:
    - ./backup:/backup
    - ./target:/target
  environment:
    - DUMPPREFIX=backup
